# backend/ai_processor.py
import os
import json
import re
from groq import Groq
from datetime import date


def generate_ddr_report(inspection_data: dict, thermal_data: dict) -> dict:
    """
    UrbanRoof DDR Generator — v4 Final.
    Corrections applied:
      - No duplicate images
      - Precise area naming
      - Correct severity classification (tile hollowness linked to moisture = Medium+)
      - Confident engineering language throughout
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError("❌ GROQ_API_KEY not found in .env file!")

    client = Groq(api_key=api_key)
    today  = date.today().strftime("%d %B %Y")

    inspection_text = inspection_data.get("text", "Not Available")
    thermal_text    = thermal_data.get("text",    "Not Available")
    insp_images     = inspection_data.get("images", [])
    therm_images    = thermal_data.get("images",   [])

    inspection_text = inspection_text[:7000] if inspection_text != "Not Available" else "Not Available"
    thermal_text    = thermal_text[:5000]    if thermal_text    != "Not Available" else "Not Available"

    # Build image inventory — filenames only, deduplicated
    seen_imgs    = set()
    image_inventory = ""
    if insp_images:
        image_inventory += "INSPECTION IMAGES:\n"
        for p in insp_images[:10]:
            name = os.path.basename(p)
            if name not in seen_imgs:
                seen_imgs.add(name)
                image_inventory += f"  - {name}\n"
    if therm_images:
        image_inventory += "THERMAL IMAGES:\n"
        for p in therm_images[:10]:
            name = os.path.basename(p)
            if name not in seen_imgs:
                seen_imgs.add(name)
                image_inventory += f"  - {name}\n"
    if not image_inventory:
        image_inventory = "No images extracted."

    # ── SYSTEM PROMPT ─────────────────────────────────────────────────────────
    system_prompt = """You are a senior building diagnostics engineer at "UrbanRoof – Building Diagnostics & Inspection" with 15+ years of field experience in structural assessment and thermal diagnostics.

You produce FINAL, CLIENT-READY Detailed Diagnostic Reports (DDR).

━━━━━━━━━━━━━━━━━━━━━━━━━━━
ABSOLUTE PROHIBITIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━
NEVER mention: AI, GPT, LLM, Groq, Llama, Machine Learning, "model", "algorithm"
NEVER use: "AI-assisted", "AI-generated", "model suggests", "the model indicates"
ALWAYS use: "System-generated diagnostic analysis" or "Generated by UrbanRoof Diagnostic System"

━━━━━━━━━━━━━━━━━━━━━━━━━━━
LANGUAGE STANDARDS — MANDATORY
━━━━━━━━━━━━━━━━━━━━━━━━━━━
Replace ALL weak phrases with confident engineering statements:

WEAK → STRONG:
❌ "may indicate moisture"        → ✔ "confirms active moisture ingress"
❌ "suggests possible leakage"    → ✔ "is consistent with concealed plumbing failure"
❌ "could be due to"              → ✔ "is attributed to"
❌ "indicates moisture retention" → ✔ "strongly indicates active moisture ingress due to concealed leakage"
❌ "possible dampness"            → ✔ "confirmed dampness with visible efflorescence"
❌ "there may be"                 → ✔ "evidence confirms"
❌ "it is recommended"            → ✔ "immediate action is required"
❌ "leakage"                      → ✔ "concealed pipe joint failure / waterproofing membrane breach"

━━━━━━━━━━━━━━━━━━━━━━━━━━━
AREA NAMING — MANDATORY
━━━━━━━━━━━━━━━━━━━━━━━━━━━
Area names MUST be precise and descriptive. Include:
- Zone + Direction + Feature
✔ "Master Bedroom — North Wall (Below Window)"
✔ "Kitchen — Ceiling Above Wet Area"
✔ "Bathroom 2 — East Wall (Behind Shower Unit)"
✔ "Living Room — North-West Corner (Floor-Wall Junction)"
❌ "Bedroom" is NOT acceptable
❌ "Kitchen" alone is NOT acceptable

━━━━━━━━━━━━━━━━━━━━━━━━━━━
SEVERITY CLASSIFICATION — MANDATORY RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━
Follow these rules WITHOUT EXCEPTION:

HIGH severity — when ANY of these apply:
  - Active water ingress or confirmed leakage
  - Structural crack with moisture involvement
  - Ceiling stain directly below wet area (bathroom/kitchen above)
  - Thermal anomaly Delta-T > 5°C

MEDIUM severity — when ANY of these apply:
  - Tile hollowness linked to moisture OR plumbing proximity (NEVER classify as Low)
  - Hairline cracks with efflorescence (salt deposits = water tracking)
  - Damp patches without active drip but with thermal evidence
  - Delta-T of 2–5°C

LOW severity — ONLY when ALL of these are true:
  - Issue is purely cosmetic
  - NO thermal anomaly present
  - NO connection to moisture, plumbing, or structure
  - Paint peeling without damp, surface scratches

━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMAGE SELECTION RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Select MAXIMUM 2 images per area from the provided inventory
- Each image filename must appear ONLY ONCE across the entire report
- If the same image is relevant to multiple areas, assign it to the most critical area only
- Do NOT fabricate image filenames — use ONLY filenames from the inventory
- If no image is relevant, write exactly: Not Available

━━━━━━━━━━━━━━━━━━━━━━━━━━━
DEDUPLICATION RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━
- State each observation ONCE in the most relevant section
- If a finding appears in both reports, merge it — do NOT list it twice
- The priority matrix must NOT repeat exact phrasing from area-wise analysis
- Recommended actions must NOT repeat root cause analysis

Return ONLY valid JSON. No markdown. No preamble. No trailing text."""

    # ── USER PROMPT ───────────────────────────────────────────────────────────
    user_prompt = f"""Generate a final client-ready DDR for UrbanRoof.

========== INSPECTION REPORT ==========
{inspection_text}

========== THERMAL REPORT ==========
{thermal_text}

========== IMAGE INVENTORY (use ONLY these filenames) ==========
{image_inventory}

========== DATE ==========
{today}

Return ONLY a valid JSON object with this EXACT structure:

{{
  "report_date": "{today}",

  "immediate_actions": [
    {{
      "action": "Precise urgent action — specific location + specific intervention + reason it cannot wait",
      "urgency": "Within 24-48 hours"
    }},
    {{
      "action": "Precise urgent action 2 — location + intervention",
      "urgency": "Within 1 week"
    }},
    {{
      "action": "Precise urgent action 3 — location + intervention",
      "urgency": "Within 2 weeks"
    }}
  ],

  "property_issue_summary": [
    "Merged finding 1 — most critical — confident engineering statement referencing specific areas",
    "Merged finding 2",
    "Merged finding 3",
    "Merged finding 4",
    "Merged finding 5"
  ],

  "issue_impact_summary": {{
    "total_areas_affected": "e.g. 4 critical zones across 2 floors",
    "primary_issue_type": "e.g. Active Water Infiltration / Concealed Plumbing Failure / Dampness",
    "risk_level": "Low / Medium / High / Critical",
    "spread": "Localized / Multi-room / Structural risk"
  }},

  "area_wise_analysis": [
    {{
      "area_name": "Precise zone description — e.g. Master Bedroom — North Wall (Below Window Sill)",
      "severity": "High / Medium / Low",
      "observed_issues": [
        "Confident, specific observation 1 — no weak language",
        "Specific observation 2 — merged from both reports if applicable"
      ],
      "thermal_evidence": "Delta-T of approximately X°C between [surface] and [reference]. This confirms [specific condition — e.g. active moisture ingress through the wall cavity, consistent with a failed waterproofing membrane at the external face].",
      "risk_if_untreated": "Specific technical consequence with timeframe — e.g. Continued moisture exposure will initiate reinforcement corrosion within 12–18 months, ultimately causing concrete spalling and loss of structural section.",
      "images": "ONLY filenames from the inventory, max 2, no duplicates across report — OR — Not Available"
    }}
  ],

  "root_cause_analysis": "3–5 sentences. Each sentence names a SPECIFIC failure mechanism. Structure: '[Location] shows [evidence], which confirms [specific cause — e.g. failed APP waterproofing membrane / corroded GI pipe joint / absence of expansion joint sealant]. The thermal data (Delta-T of Xdeg C at [location]) corroborates active moisture migration through [specific path]. [Third cause if applicable].' Use confident engineering language. No hedging.",

  "priority_matrix": {{
    "high": [
      "Issue — Precise location — Specific immediate risk (do not repeat exact wording from area analysis)"
    ],
    "medium": [
      "Issue — Precise location — Consequence if ignored within X months (tile hollowness near wet areas goes here, not Low)"
    ],
    "low": [
      "Purely cosmetic issue — Precise location — only if NO moisture or structural link"
    ]
  }},

  "recommended_action_plan": [
    "Step 1: [Specific action] — [Exact location] — [Material or method if determinable from data]",
    "Step 2: ...",
    "Step 3: ...",
    "Step 4: ...",
    "Step 5: ...",
    "Step 6: ..."
  ],

  "additional_insights": "3–4 sentences. Reference specific areas and data. Cover: systemic patterns, maintenance gaps, building-age observations, structural concerns. Confident tone — no hedging.",

  "missing_or_unclear_data": [
    "Specific missing data item 1 — e.g. Thermal scan of external north-facing wall not included",
    "Specific missing data item 2 — e.g. Age of concealed plumbing not stated in inspection report",
    "Specific missing data item 3 — e.g. No moisture meter readings provided for affected walls"
  ]
}}
"""

    print("📡 Calling Groq — UrbanRoof DDR v4 (final corrections)...")

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt}
        ],
        temperature=0.1,
        max_tokens=4096,
    )

    raw = response.choices[0].message.content
    print(f"✅ Response received ({len(raw)} chars)")

    # Strip markdown fences
    raw = re.sub(r"```json|```", "", raw).strip()

    # Extract JSON block robustly
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        raw = match.group(0)

    try:
        ddr = json.loads(raw)
        # Post-process: deduplicate images across all areas
        ddr = _deduplicate_images(ddr)
        return ddr
    except json.JSONDecodeError as e:
        print(f"⚠️ JSON parse error: {e}\nRaw (first 500):\n{raw[:500]}")
        return _fallback(today, raw)


def _deduplicate_images(ddr: dict) -> dict:
    """
    Post-processing pass: ensure each image filename appears only once
    across all area_wise_analysis entries. First area to claim it keeps it.
    """
    used = set()
    for area in ddr.get("area_wise_analysis", []):
        raw = area.get("images", "")
        if not raw or raw.strip().lower() in ("not available", "n/a", ""):
            area["images"] = "Not Available"
            continue

        names  = [x.strip() for x in raw.replace(";", ",").split(",") if x.strip()]
        unique = []
        for name in names:
            if name not in used:
                used.add(name)
                unique.append(name)
            if len(unique) == 2:
                break

        area["images"] = ", ".join(unique) if unique else "Not Available"
    return ddr


def _fallback(today: str, raw: str) -> dict:
    return {
        "report_date": today,
        "immediate_actions": [
            {"action": "Report parsing failed. Retry with text-extractable PDFs.", "urgency": "N/A"}
        ],
        "property_issue_summary": ["Report generation failed — see additional_insights for raw output."],
        "issue_impact_summary": {
            "total_areas_affected": "Not Available",
            "primary_issue_type":   "Not Available",
            "risk_level":           "Not Available",
            "spread":               "Not Available"
        },
        "area_wise_analysis": [],
        "root_cause_analysis": "Not Available — report parsing failed.",
        "priority_matrix": {"high": [], "medium": [], "low": []},
        "recommended_action_plan": [
            "Step 1: Retry with OCR-enabled, text-extractable PDFs.",
            "Step 2: Contact UrbanRoof support if the issue persists."
        ],
        "additional_insights": raw[:1500],
        "missing_or_unclear_data": [
            "JSON parsing failed — PDFs may be image-only (scanned).",
            "Use OCR-processed PDFs for best results."
        ]
    }