// src/components/ReportView.jsx

export default function ReportView({ reportHtml, reportUrl, inspectionName, thermalName, onReset }) {
  return (
    <div className="report-page">

      {/* Top bar */}
      <div className="report-topbar">
        <div className="report-topbar-left">
          <h2>Diagnostic Report Ready</h2>
          <p>Your Detailed Diagnostic Report has been generated successfully.</p>
        </div>

        <div className="report-topbar-actions">
          <button className="btn-outline" onClick={onReset}>
            ← New Report
          </button>
          <a
            href={reportUrl}
            download="UrbanRoof_DDR_Report.html"
            className="btn-primary-sm"
          >
            ⬇ Download Report
          </a>
          <a
            href={reportUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="btn-outline"
          >
            ↗ Open Full Screen
          </a>
        </div>
      </div>

      {/* Source file chips */}
      <div className="file-chips">
        <span className="file-chip">📄 {inspectionName || "Inspection Report"}</span>
        <span className="file-chip">🌡️ {thermalName || "Thermal Report"}</span>
        <span className="file-chip" style={{
          background: "var(--sev-low-bg)",
          borderColor: "var(--sev-low-bd)",
          color: "var(--sev-low-text)",
          fontWeight: 700,
        }}>
          ✓ Report Generated
        </span>
      </div>

      {/* Report iframe */}
      <div className="report-iframe-wrap">
        <iframe
          className="report-iframe"
          srcDoc={reportHtml}
          title="UrbanRoof Diagnostic Report"
          sandbox="allow-same-origin"
        />
      </div>

      {/* Bottom note */}
      <p style={{
        textAlign: "center",
        marginTop: "16px",
        fontSize: "0.77rem",
        color: "var(--text-muted)",
      }}>
        Generated by UrbanRoof Diagnostic System · All findings should be verified by a licensed engineer before action.
      </p>

    </div>
  );
}