// src/App.jsx
import { useState, useEffect } from "react";
import axios from "axios";
import Header from "./components/Header";
import UploadSection from "./components/UploadSection";
import ProcessingState from "./components/ProcessingState";
import ReportView from "./components/ReportView";
import "./App.css";

const BACKEND_URL = "";  // Uses Vite proxy — see vite.config.js

export default function App() {
  const [theme, setTheme]               = useState("light");
  const [inspectionFile, setInspection] = useState(null);
  const [thermalFile, setThermal]       = useState(null);
  const [status, setStatus]             = useState("idle"); // idle | processing | done | error
  const [errorMsg, setErrorMsg]         = useState("");
  const [reportUrl, setReportUrl]       = useState(null);
  const [reportHtml, setReportHtml]     = useState("");

  // Persist theme
  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
  }, [theme]);

  const toggleTheme = () => setTheme(t => t === "light" ? "dark" : "light");

  const handleGenerate = async () => {
    if (!inspectionFile || !thermalFile) {
      setErrorMsg("Please upload both the Inspection Report and Thermal Report before continuing.");
      return;
    }
    if (!inspectionFile.name.endsWith(".pdf") || !thermalFile.name.endsWith(".pdf")) {
      setErrorMsg("Both files must be in PDF format.");
      return;
    }

    setErrorMsg("");
    setStatus("processing");
    setReportUrl(null);
    setReportHtml("");

    try {
      const formData = new FormData();
      formData.append("inspection_report", inspectionFile);
      formData.append("thermal_report",    thermalFile);

      const response = await axios.post(`${BACKEND_URL}/generate-ddr`, formData, {
        headers:      { "Content-Type": "multipart/form-data" },
        responseType: "blob",
        timeout:      180000,
      });

      const blob    = new Blob([response.data], { type: "text/html" });
      const url     = URL.createObjectURL(blob);
      const html    = await blob.text();

      setReportUrl(url);
      setReportHtml(html);
      setStatus("done");
    } catch (err) {
      setStatus("error");
      if (err.code === "ERR_NETWORK" || err.message?.includes("Network Error")) {
        setErrorMsg("Unable to connect to the server. Please ensure the backend service is running.");
      } else if (err.code === "ECONNABORTED") {
        setErrorMsg("Request timed out. The reports may be too large. Please try smaller files.");
      } else if (err.response?.status === 500) {
        setErrorMsg("The server encountered an error while processing. Please check your files and retry.");
      } else {
        setErrorMsg(`An error occurred: ${err.message}`);
      }
    }
  };

  const handleReset = () => {
    setInspection(null);
    setThermal(null);
    setStatus("idle");
    setErrorMsg("");
    setReportUrl(null);
    setReportHtml("");
  };

  return (
    <div className="app-root">
      <Header theme={theme} onToggleTheme={toggleTheme} />

      <main className="main-content">
        {status === "idle" || status === "error" ? (
          <UploadSection
            inspectionFile={inspectionFile}
            thermalFile={thermalFile}
            onInspectionChange={setInspection}
            onThermalChange={setThermal}
            onGenerate={handleGenerate}
            errorMsg={errorMsg}
          />
        ) : status === "processing" ? (
          <ProcessingState />
        ) : (
          <ReportView
            reportHtml={reportHtml}
            reportUrl={reportUrl}
            inspectionName={inspectionFile?.name}
            thermalName={thermalFile?.name}
            onReset={handleReset}
          />
        )}
      </main>

      <footer className="app-footer">
        <span>© {new Date().getFullYear()} UrbanRoof — Building Diagnostics &amp; Inspection</span>
        <span className="footer-sep">·</span>
        <span>Generated by UrbanRoof Diagnostic System</span>
      </footer>
    </div>
  );
}